name: CI

on:
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-default:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run clippy
        run: cargo clippy --verbose --tests --examples --benches -- --deny warnings
  build-tokio:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --features async_tokio --verbose
      - name: Run tests
        run: cargo test --features async_tokio --verbose
      - name: Run clippy
        run: cargo clippy --features async_tokio --verbose --tests --examples --benches -- --deny warnings
